### ISSUE TITLE
ugly error message

### ISSUE THREAD

**Issue by shriram** [brownplt/pyret-lang#815]
```
> r1 :: Reactor = r
Name not found in globals.types: Reactor"
```

"globals.types" should never be seen from the outside.

**Comment by jpolitz** [comment]
Thanks, that's because of a silly bug where the type environment and modules had a gap in agreeing on names.

This is mostly fixed by https://github.com/brownplt/pyret-lang/commit/88732aa206e0a81261c695eaa0993e677da1dde5, but @mkolosick, it is another place where the type checker now will be confused about type aliases vs. datatypes, so will need to iron that out.  (Currently, this makes the type checker look for an alias that isn't there, while the dynamic namespace works fine).

**Comment by sorawee** [comment]
@jpolitz it doesn't seem to be fixed. I still see same error message. See also #1013
